### ISSUE TITLE
[Steam>Development] Window failing to manifest on desktop

### ISSUE THREAD

**Issue by ZephSolaris** [nginetechnologies/sceneri-issue-tracker#24]
When launching via Steam with development branch, Sceneri runs and consumes CPU, but fails to generate a window.
Application must be stopped via the Steam GUI or Task Manager.

Expected behavior is for a window to manifest so there's something in the task bar.
Doesn't matter to me what's in that window, but I imagine a 'trying to connect to server' modal or some path towards local offline functionality would be nice.

It's possible that this could be related to your servers being down for the migration.  Will test again when migration is complete and update if change is noticed.

Staging branch operates as expected.

**Comment by ifiddynine** [comment]
@ZephSolaris does this still happen in the latest build?

**Comment by ZephSolaris** [comment]
On the 22 November, 2024 Development branch build, there is new behavior.

The editor now loads and closes before opening a window.  Looking at the log files, I'm seeing the analytics plugin starting to load, but never finish.

Is there a way to make the log files more verbose?

**Comment by ifiddynine** [comment]
Irony was that the new crash reporter was crashing while trying to add new info - should be fixed in the next build!
